### 학습목표
 - random 서브모듈 함수를 통해 ndarray 생성하기

In [1]:
import numpy as np

#### random 서브모듈

#### rand 함수
 - 0, 1사이의 분포로 랜덤한 ndarray 생성

In [5]:
np.random.rand(2, 3)

array([[0.40396413, 0.34568523, 0.68092625],
       [0.39891987, 0.52414831, 0.20886615]])

#### randn함수
 - n: normal distribution(정규분포)
 - 정규분포로 샘플링된 랜덤 ndarray 생성

In [9]:
np.random.randn(3, 4, 2)

array([[[-0.72619175,  1.0357264 ],
        [-0.70896234, -0.29940465],
        [-0.47930181, -1.13174308],
        [-1.10768231,  0.99867834]],

       [[ 0.96576449,  1.06191664],
        [-0.53817376,  0.54891476],
        [-1.16683369, -0.13436309],
        [-1.34679593,  0.5978272 ]],

       [[-0.58618401,  0.16579027],
        [-0.84114744, -2.97188615],
        [ 2.59170647,  0.23179896],
        [-0.36411628, -2.33484749]]])

In [10]:
np.random.randn(5)

array([ 0.43298685, -1.60001787,  1.04584215,  1.25549922,  0.3912139 ])

#### randint 함수
 - 특정 정수 사이에서 랜덤하게 샘플링

In [19]:
np.random.randint(1, 100, size=(3, 5 , 2))

array([[[ 7,  2],
        [94, 15],
        [38, 40],
        [88,  2],
        [58, 87]],

       [[62, 36],
        [84, 79],
        [31, 34],
        [94, 83],
        [10, 25]],

       [[77, 12],
        [42, 67],
        [10, 34],
        [72, 78],
        [10, 27]]])

#### seed 함수
 - 랜덤한 값을 동일하게 다시 생성하고자 할때 사용

In [40]:
np.random.seed(10)


In [41]:
np.random.randn(3, 4)

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556,  0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021,  0.43302619,  1.20303737]])

#### choice
 - 주어진 1차원 ndarray로 부터 랜덤으로 샘플링
 - 정수가 주어진 경우, np.arange(해당숫자)로 간주

In [49]:
np.random.choice(100, size = (3, 4), replace = False)

array([[81, 10, 90, 67],
       [55, 36, 98, 65],
       [60, 43, 35, 96]])

In [52]:
x = np.array([1, 2, 3, 1.5, 2.6, 4.9])

np.random.choice(x, size=(2, 2), replace = False)

array([[1. , 3. ],
       [2. , 4.9]])

#### 확률분포에 따른 ndarray 생성
 - uniform
 - normal 등등

In [53]:
np.random.uniform(1.0, 3.0, size=(4, 5))

array([[2.77165419, 1.73072994, 1.4375387 , 2.50499234, 1.21375917],
       [2.48920648, 1.93957059, 2.19651134, 1.29524038, 1.36806964],
       [2.29014425, 1.09725601, 1.49722502, 2.08481703, 1.45354669],
       [1.76282307, 2.84446557, 2.85071375, 2.13349985, 2.06694177]])

In [60]:
x = np.random.normal(size=(2, 4))

y = np.random.randn(3, 5)

print(x)
print(y)

[[ 2.46101489 -2.39680298  4.34815109  3.3274474 ]
 [ 0.73485281  0.41950838 -0.90706484  2.17608119]]
[[ 0.06880147  1.4120643  -0.68621561  0.54794393 -0.03638254]
 [-0.84701625  1.90230404  0.27960539  0.6202545  -1.06856771]
 [-0.72262073  0.08413956 -0.58445516  0.60202227  0.43836524]]
