### 학습목표
 1. 인덱싱과 슬라이싱 활용하기


In [1]:
import numpy as np

#### 인덱싱
 - 파이썬 리스트와 동일한 개념으로 사용
 - ,를 사용하여 각 차원의 인덱스에 접근 가능

 * 1차원 벡터 인덱싱

In [2]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
x[3] = 300
print(x)

[  0   1   2 300   4   5   6   7   8   9]


* 2차원 행렬 인덱싱

In [9]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [20]:
x[1, -3]

7

* 3차원 텐서 인덱싱

In [21]:
x = np.arange(36).reshape(3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [25]:
x[1, 2]

array([18, 19, 20])

#### 슬라이싱
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - ,를 사용하여 각 차원 별로 슬라이싱 가능

* 1차원 벡터 슬라이싱

In [26]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
x[1:]

array([1, 2, 3, 4, 5, 6])

* 2차원 행렬 슬라이싱

In [28]:
x = np.arange(10).reshape(2, 5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
x[:, 1:4]

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
x[0, :2]

array([0, 1])

In [32]:
x[:1, :2]

array([[0, 1]])

* 3차원 텐서 슬라이싱

In [35]:
x = np.arange(54).reshape(2, 9, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]]

 [[27 28 29]
  [30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]
  [48 49 50]
  [51 52 53]]]


In [36]:
x[:1, :2, :]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [37]:
x[0, :2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [38]:
y = np.arange(125).reshape(5, 5, 5)

print(y)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]


In [40]:
y[2:3, :, 0:1]

array([[[50],
        [55],
        [60],
        [65],
        [70]]])

In [41]:
y[2, :, 0:1]

array([[50],
       [55],
       [60],
       [65],
       [70]])