## 학습목표
 1. numpy에서 자주 사용되는 함수들을 사용해보기

In [11]:
import numpy as np

#### numpy documentation
 - [numpy 공식 문서 링크](https://www.numpy.org/devdocs/reference/)
 - numpy에서 제공되는 함수등에 대한 문서

In [28]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print()
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[0.12354539 0.45310618 0.32425688 0.4526175  0.25444184]
 [0.51701518 0.04688756 0.0983965  0.6555473  0.2812549 ]
 [0.42710188 0.98242323 0.84380307 0.01026531 0.48879168]]


#### 연산 함수
 - add, substract, multiply, divide

In [13]:
np.add(x,y)


array([[ 0.85655183,  1.99753144,  2.9232208 ,  3.6713419 ,  4.45456733],
       [ 5.77568593,  6.00082219,  7.87291331,  8.27200314,  9.45091799],
       [10.63275885, 11.03685192, 12.30950617, 13.95014739, 14.4831794 ]])

In [26]:
print(x + y)
print(x - y)

[[ 0.85655183  1.99753144  2.9232208   3.6713419   4.45456733]
 [ 5.77568593  6.00082219  7.87291331  8.27200314  9.45091799]
 [10.63275885 11.03685192 12.30950617 13.95014739 14.4831794 ]]
[[-8.56551830e-01  2.46855981e-03  1.07677920e+00  2.32865810e+00
   3.54543267e+00]
 [ 4.22431407e+00  5.99917781e+00  6.12708669e+00  7.72799686e+00
   8.54908201e+00]
 [ 9.36724115e+00  1.09631481e+01  1.16904938e+01  1.20498526e+01
   1.35168206e+01]]


In [22]:
np.multiply(x, y)

array([[0.00000000e+00, 9.97531440e-01, 1.84644160e+00, 2.01402571e+00,
        1.81826933e+00],
       [3.87842965e+00, 4.93312101e-03, 6.11039320e+00, 2.17602513e+00,
        4.05826193e+00],
       [6.32758846e+00, 4.05371148e-01, 3.71407398e+00, 1.23519161e+01,
        6.76451167e+00]])

In [16]:
np.divide(x, y)

array([[0.00000000e+00, 1.00247467e+00, 2.16632900e+00, 4.46866192e+00,
        8.79957644e+00],
       [6.44590781e+00, 7.29761137e+03, 8.01912388e+00, 2.94114250e+01,
        1.99592834e+01],
       [1.58038091e+01, 2.98491890e+02, 3.87714409e+01, 1.36820878e+01,
        2.89747449e+01]])

#### 통계 함수
 - 평균, 분산, 중앙, 최대, 최소값 등등 통계 관련된 함수가 내장

In [29]:
print(y)

[[0.12354539 0.45310618 0.32425688 0.4526175  0.25444184]
 [0.51701518 0.04688756 0.0983965  0.6555473  0.2812549 ]
 [0.42710188 0.98242323 0.84380307 0.01026531 0.48879168]]


In [30]:
np.mean(y)

0.39729696053176333

In [31]:
y.mean()

0.39729696053176333

In [32]:
np.max(y)

0.9824232255480139

In [33]:
np.argmax(y)

11

In [41]:
def bubble(data):
    for idx in range(len(data)-1):
        swap = False
        for idx2 in range(len(data) - idx - 1):
            if data[idx2] > data[idx2 + 1]:
                data[idx2], data[idx2+1] = data[idx2+1], data[idx2]
                swap = True
        if swap == False:
            break
    return data
t = y.flatten()
bubble(t)
print(t.flatten())

[0.01026531 0.04688756 0.0983965  0.12354539 0.25444184 0.2812549
 0.32425688 0.42710188 0.4526175  0.45310618 0.48879168 0.51701518
 0.6555473  0.84380307 0.98242323]


In [42]:
np.var(y)
np.median(y)
np.std(y)

0.27255221402493085

#### 집계함수
 - 합계(sum), 누적합계(cumsum) 등등 계산 가능

In [46]:
y

array([[0.12354539, 0.45310618, 0.32425688, 0.4526175 , 0.25444184],
       [0.51701518, 0.04688756, 0.0983965 , 0.6555473 , 0.2812549 ],
       [0.42710188, 0.98242323, 0.84380307, 0.01026531, 0.48879168]])

In [47]:

np.sum(y)
np.cumsum(y)

array([0.12354539, 0.57665157, 0.90090845, 1.35352595, 1.60796779,
       2.12498297, 2.17187053, 2.27026703, 2.92581434, 3.20706923,
       3.63417112, 4.61659434, 5.46039742, 5.47066273, 5.95945441])

In [51]:
np.sum(y, axis = 0)
np.sum(y, axis = 1)


array([1.60796779, 1.59910144, 2.75238517])

#### any, all 함수
 - any: 특정 조건을 만족하는 것이 하나라도 있으면 True, 아니면 False
 - all: 모든 원소가 특정 조건을 만족한다면 True, 아니면 False

In [ ]:
np.std(np.arange(1, 5))

In [55]:
z > 0

array([ True,  True,  True,  True, False,  True,  True, False,  True,
       False])

In [54]:
z= np.random.randn(10)
print(z)
np.any(z>0)

[ 0.38502065  0.63997471  0.05201431  0.65552269 -0.41662034  0.38665355
  1.08109747 -0.55487034  0.83342609 -0.22639881]


True

In [57]:
np.all(z>0)

False

In [58]:
np.all(z != 0)

True

#### where 함수
 - 조건에 따라 선별적으로 값을 선택 가능
 - 사용 예) 음수인경우는 0, 나머지는 그대로 값을 쓰는 경우

In [59]:
z = np.random.randn(10)
print(z)

[ 1.49887816  0.763825   -0.09774488  1.61999544 -0.43898987  0.52923961
  0.6163932  -0.53271396 -0.83121452  0.38259516]


In [60]:
np.where(z > 0, z, 0)

array([1.49887816, 0.763825  , 0.        , 1.61999544, 0.        ,
       0.52923961, 0.6163932 , 0.        , 0.        , 0.38259516])