## 학습목표
 1. 브로드캐스팅의 이해

In [1]:
import numpy as np

#### 브로드캐스팅
  - Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - 연산되는 두 ndarray가 다른 Shape을 갖는 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    


#### 브로드캐스팅 Rule
 - [공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 Shape이 같거나, 차원 중 값이 1인 것이 존재하면 가능

![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg 

* Shape이 같은 경우의 연산

In [3]:
x = np.arange(15).reshape(3, 5)
y = np.random.rand(15).reshape(3, 5)
print(x)
print(y)
x + y


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[0.22194956 0.89688227 0.12269484 0.11898318 0.19397359]
 [0.84442836 0.24596391 0.12234904 0.8453423  0.46823762]
 [0.64063178 0.60490561 0.69796621 0.01361506 0.18255745]]


array([[ 0.22194956,  1.89688227,  2.12269484,  3.11898318,  4.19397359],
       [ 5.84442836,  6.24596391,  7.12234904,  8.8453423 ,  9.46823762],
       [10.64063178, 11.60490561, 12.69796621, 13.01361506, 14.18255745]])

* Scalar(상수)와의 연산

In [6]:
x % 2 == 0

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

* Shape이 다른 경우 연산

In [14]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)
c = np.arange(1000, 1004)
d = b.reshape(1, 3)

print(a)
print()
print(b)
print(d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[100 101 102]
[[100 101 102]]


In [8]:
a + b

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [10]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [15]:
a + d

array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [16]:
z = np.arange(30).reshape(2, 5, 3)
y = np.arange(100, 103)

print(z)
print(y)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[100 101 102]


In [20]:
z - y

array([[[-100, -100, -100],
        [ -97,  -97,  -97],
        [ -94,  -94,  -94],
        [ -91,  -91,  -91],
        [ -88,  -88,  -88]],

       [[ -85,  -85,  -85],
        [ -82,  -82,  -82],
        [ -79,  -79,  -79],
        [ -76,  -76,  -76],
        [ -73,  -73,  -73]]])